version: '3'

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env      
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - frankenapi-net    
    depends_on:
      - db
    restart: unless-stopped
    command: npm run dev

  db:
    image: postgres:14.5-bullseye
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - frankenapi-net
    volumes:
      - frankenapi-data:/var/lib/postgresql/data
      - ./docker/postgres:/docker-entrypoint-initdb.d
    restart: unless-stopped

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080    
    networks:
      - frankenapi-net

networks:
  frankenapi-net:

volumes:
  frankenapi-data: